# Generated by Django 2.2.13 on 2020-08-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200801_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='new', max_length=15, verbose_name='Модерация'),
        ),
    ]
