# Generated by Django 2.2.13 on 2020-08-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200801_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.EmailField(default='Email Address', max_length=40, verbose_name='Емейл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Name', max_length=200, verbose_name='Имя'),
        ),
    ]
